### ISSUE TITLE
Add UNDO button 

### ISSUE THREAD

**Issue by nguyenhanhquyen** [openforis/collect-earth-online#100]
Hi,
In case user accidentally assign plot incorrectly/ or want to change their interpretation after saving them
can the user or project manager could track back to the incorrect plots in the database, or would be possible to have an Undo button on the interface of the tool?

Thanks,

**Comment by sirmspencer** [comment]
Changes in PR #187 allow the user to go back through plots that the same user has analyzed.  The user can then change any of the answers and save again.
