### ISSUE TITLE
Add the planet controller only when the layer is used instead of adding and removing it initially.

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#1001]
See setBaseMapSource in collection.js.  We shouldnt need to remove it every time setBaseMapSource is called.  I would suggest adding it in collectionMenuControls in the menu control that uses it.

**Comment by rfontanarosa** [comment]
**setBaseMapSource** is called every time a user change the imagery options from the sidebar in the collection page.
the content of the planet-layer-switcher also depends on start date and end date.

- the planet-layer-switcher Control is removed when a user change imagery
- the planet-layer-switcher Control is removed when a user change the dates and update the map of planet daily imagery
- the planet-layer-switcher is created by createSource when a  PlanetDaily imagery is selected

![Schermata 2021-01-12 alle 14 16 07](https://user-images.githubusercontent.com/10047945/104468635-4ad9e900-557d-11eb-8ccc-b018d1f3a8bc.png)
