### ISSUE TITLE
Clear dot colors when adding more than one attribute

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#101]
When adding more than one attribute to the points in a plot, the color coding from the first attribute remains in place when adding the second attribute, which becomes quite confusing. It would be helpful to have a way to wipe the color coding after the first attribute is added so that you have a clean slate to work with when adding the second attribute. Perhaps a button to "start" each subsequent attribute that would wipe the colors. Alternatively, you might provide a way to select points and add two attributes at the same time. Karis Tenneson may have some good insights into how to do this since this was implemented in RSAC's tool.

**Comment by sirmspencer** [comment]
The new  UI for selecting plot samples has been significantly revamped.  Colors will remain as long as the user is still on the same question.  As the user goes to a sub question the colors will switch to that questions (so color if some are answered or no colors if just getting to the question).  In addition only the samples available to select are shown.
