### ISSUE TITLE
Add ability to add hierarchies in the class structure

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#102]
It would be helpful to be able to add hierarchies in the class structure, which is currently available in Collect Earth desktop. This is particularly valuable when there are a lot of classes involved. So, for example, the user could select a broad class like forest and then have the options of mature forest, secondary forest, mangrove, etc. appear as options rather than having to navigate through the entire list of all classes.

**Comment by snasaio** [comment]
The current published version of the application now allows this.
