### ISSUE TITLE
Additional issues with Survey Rules

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#1026]
Following from #996 

My test project: https://collect.earth/review-project?projectId=19707

- [ ] When adding multiple Sum of Answers rules, the Valid sum will sometimes change for already added rules when a new Sum of Answers rule is added. To replicate this issue, select survey questions, add 100 as the valid sum. Add Survey Rule. Then change valid sum to 99. Add Survey Rule. The Valid Sum for previous questions may change. The issue with changing previous Valid Sum seems also partly tied to updating previously input rules. That is, if you keep the questions the same, but then change the Valid Sum, the Valid Sum will update in the already input rule. However if you change the questions, you will get a new rule and previous Valid Sum will only occasionally change. I wonder if there's an if statement evaluating incorrectly or something.
- [x] If possible, add 'this rule has already been added' error pop up to avoid 'Add Survey Rule' silently failing when the user tries to add a duplicate rule.
- [x]  If possible, add 'you must add at least two questions to each set' error pop up to avoid 'Add Survey Rule' silently failing when the user tries to add a Matching Sums rule without enough questions in each set.

**Comment by kdyson** [comment]
Additional feature request as an alternative to adding an error rule above

- [ ] For Matching Sums, instead of requiring two answers for both parts, require 2 for one part and allow the other part to have only one. (e.g. so sum of deciduous and coniferous forest == total forest).

**Comment by sirmspencer** [comment]
About the Valid Sums issue, he says that each time he adds a new rule of incompatible answers, the valid sum rules above are deleted. This -> ("The issue with changing previous Valid Sum seems ...) has nothing to do with it. He has to re-enter the valid sum rules every time he adds a new rule of incompatible answers...
