### ISSUE TITLE
Add validator for new XYZ source

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#1030]

**Comment by rfontanarosa** [comment]
which validator should be added? we don't have any validator for url, only for url which contains query string.
do we need a generic url validator? is that parameter required?

**Comment by sirmspencer** [comment]
The XYZ source take a single url.  This is different from WMS.  For XYZ we need to check that there is an x y and a z.  In the URL they should be `{x}` `{y}` and `{z}`.  Also note that any of the tree can be negative like `{-x}`
