### ISSUE TITLE
Account link returns 'HTTP Status 404 - /account/151'

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#104]
Hello,
When I sign in as a user (not as admin) and try to open the Account page, I get a page with the message that 'The resource is not available (HTTP Status 404 - /account/151)'

**Comment by lambdatronic** [comment]
Hi Karis,

I just logged in as my regular user (gjohnson@sig-gis.com) and clicked on the Account link but did not see any errors. I also tried navigating manually to /account/151, and it works correctly for me. The account page code doesn't check whether a user is an admin or not, so I'm not sure why you would see a difference here. Perhaps you could provide some further context (or a screenshot)?

**Comment by karistenneson** [comment]
Weird. I just tried again and it connects to the correct page. I guess it's resolved.
