### ISSUE TITLE
Create Institution > Indicator for Required Fields

### ISSUE THREAD

**Issue by rjsheperd** [openforis/collect-earth-online#1093]
### Steps to Reproduce
1. Go to https://collect.earth
2. Sign in/Create account
3. Go to "Create an Institution"
4. Fill in Title field, but not Description
5. "Create Institution" button is disabled, but there are no warnings/indicators that Title AND Description are required fields.

### Screenshots
![Cursor_and_Collect_Earth_Online](https://user-images.githubusercontent.com/1829313/109210641-f58b1d00-7761-11eb-875b-e007e578aa63.png)

**Comment by sirmspencer** [comment]
I prefer not to disable buttons, but instead show an error message when clicked.  Feel free to make that change here.
