### ISSUE TITLE
Institution > Title / Description have no Char Limit

### ISSUE THREAD

**Issue by rjsheperd** [openforis/collect-earth-online#1094]
### Steps to Reproduce
1. Go to https://collect.earth
2. Create/Edit an Institution
3. Add a very long Title/Description
4. Validation does not prevent a super long Title/Description

### Screenshots
![Cursor_and_Collect_Earth_Online](https://user-images.githubusercontent.com/1829313/109217143-4d2d8680-776a-11eb-9b8d-1322215a925b.png)

**Comment by sirmspencer** [comment]
See #1093.  I would suggest add that check when you are checking required fields.  Don't disable the save button instead check for required fields and this error.
