### ISSUE TITLE
Project > Create > "Hold CMD to Create BBOX" on Mac

### ISSUE THREAD

**Issue by rjsheperd** [openforis/collect-earth-online#1096]
### Purpose
As a user on Mac, I have to use CMD to draw the bounding box. Would be nice if the instructions would reflect that

### Screenshot
![Collect_Earth_Online](https://user-images.githubusercontent.com/1829313/109229919-da77d780-7778-11eb-91fe-3ed65b1394bb.png)

**Comment by sirmspencer** [comment]
window.navigator.platform.toLowerCase.startsWith("mac")
