### ISSUE TITLE
Verify time zones in SQL, JS, and CSV

### ISSUE THREAD

**Issue by rjsheperd** [openforis/collect-earth-online#1105]
Times should be consistently UTC or local time.

Project > CSV Output > collection_time Timezone should be in UTC

### Steps to Reproduce
1. Login as a User
2. Survey a plot in a project
3. Download the project's plots
4. Verify the `collection_time` time zone

### Screenshot
![ceo-Another-Watershed-plot-data-2021-03-02__2_](https://user-images.githubusercontent.com/1829313/109706791-3d3cea80-7b4e-11eb-9571-413a1df3b787.png)

Project Review > Publish Project

### Steps to Reproduce
1. Login as admin of an institution
2. Go to the review project page for a unpublished project
3. Have the local time be a different day that UTC time
4. Click publish
5. Publish date is the UTC date not local date.

**Comment by sirmspencer** [comment]
I think its JS that is timezone specific. Checkout `;;; Time processing` in the dev branch (assuming the match drop branch is merged)

**Comment by rjsheperd** [comment]
#### CSV Downloading issue:
So here are some of the relevant bits:
1. Postgres has it's own `TIMEZONE` configuration, which on the Prod/Dev is currently set to `UTC`
2. The client generates the initial `collection_start` timestamp in UTC (which is turned into a timestamp by `projects.clj`), while the server updates the `collection_time` timestamp
3. When the CSV is downloaded, the `collection_time` is formatted to the `"Y-M-D HH:MM` format in `projects.clj`

If we wanted to simply change the formatting of the `collection_time` to use the current client's Timezone, we could pass that as a parameter in the request to `/dump-project-aggregate-data` and shift the Timezone accordingly. If we do that, it would be useful to include the timezone in the header.

#### Publish/Create Project Dates mismatch:
This looks both the `created` and `published` are both dates (not timestamps) and set using Postgres `now()` function. This means whenever you create or publish a project you will end up creating it on the date that the Postgres instance is set to, not your local date. 

The first step to remedy this would require a change of the existing projects table to use `timestamp` rather than `date` for both `created_date` and `published_date.` Next, we would have to figure out where the timestamp should be formatted. If we wanted the backend to handle the formatting, maybe we could have User's set a timezone in their user settings. We could also store their current client's timezone in a session variable when they visit the site. Alternatively, we could format the date in the front-end using something like [getTimeZoneOffset](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset)
