### ISSUE TITLE
NAIP request

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#111]
Hello,
I had a request from foresters working on Collaborative Forest Landscape Restoration Programs in the US to use the tool. Can we add in the NAIP imagery feed as a default option (or should we as the USFS institution set this up?)

**Comment by lambdatronic** [comment]
You should add new imagery feeds to your institutions. It looks like a lot of the site-wide public imagery is going to disappear soon after the talks in Rome.
