### ISSUE TITLE
Home > Project List > Edit Text not centered

### ISSUE THREAD

**Issue by rjsheperd** [openforis/collect-earth-online#1116]
Edit text on home page project edit button is misaligned (not centered)

**Comment by sirmspencer** [comment]
On what browser and system?  Its is center on Chrome with linux

**Comment by rjsheperd** [comment]
Issue is visible on Chrome with a 13" display:
<img width="577" alt="Collect_Earth_Online" src="https://user-images.githubusercontent.com/1829313/110670895-beb1ff80-8182-11eb-9247-9eccfd3db52f.png">
