### ISSUE TITLE
Plot Information panel replaces "Y" or "y" with "lat"

### ISSUE THREAD

**Issue by jdilger** [openforis/collect-earth-online#1151]
When using a csv for plot generation with the "Show Extra Plot Columns on Collection Page"  columns that have a "y" character are replaced with "lat" when viewed in the Plot Information panel when collecting. 

e.g. original -> displayed
       coded_year -> coded_latear
       fcdmYear -> fcdmlatear

**Comment by sirmspencer** [comment]
Thank you.  This is a known bug and a fix will be in the next release.

**Comment by jdilger** [comment]
Awesome, happy to hear. Thanks!

**Comment by sirmspencer** [comment]
@jdilger This fix should be deployed now.  Can you verify that it satisfies your issue?

**Comment by jdilger** [comment]
@sirmspencer fix looks great and satisfies my issue 👍 Thanks again
