### ISSUE TITLE
Require TOS Acceptance

### ISSUE THREAD

**Issue by rjsheperd** [openforis/collect-earth-online#1155]
Require acceptance of the TOS (See: #1153 ) when:

- [ ] Registering a new user
- [ ] Creating a new institution
- [ ] Creating a new project

**Comment by sirmspencer** [comment]
![image](https://user-images.githubusercontent.com/33734037/111847775-c2eac500-88c6-11eb-8922-9c7bdf804582.png)

**Comment by sirmspencer** [comment]
![image](https://user-images.githubusercontent.com/33734037/111847818-e31a8400-88c6-11eb-9422-ac0a18c25148.png)
 
Or make the button smaller
![image](https://user-images.githubusercontent.com/33734037/111847847-f4fc2700-88c6-11eb-906f-0cbf0aad45e8.png)

**Comment by sirmspencer** [comment]
![image](https://user-images.githubusercontent.com/33734037/111847898-0e04d800-88c7-11eb-92df-4ca9b0b99f9a.png)
