### ISSUE TITLE
GeoDash Planet

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#1165]
Planet background imagery for GeoDash uses Oct. 2020 data and cannot be changed. 

Broader issue--for date dependent background imagery, this should probably have date input capabilities.

**Comment by sirmspencer** [comment]
What planet?  What project?

**Comment by kdyson** [comment]
Apologies, this is for the Planet NICFI source, but applies to any date dependent background imagery. Here's my test project https://ceodev.servirglobal.net/review-project?projectId=4707 and the link to the geodash: https://ceodev.servirglobal.net/widget-layout-editor?editable=true&institutionId=356&projectId=4707
