### ISSUE TITLE
Selected subplots don't seem to register anymore

### ISSUE THREAD

**Issue by JohnMBrandt** [openforis/collect-earth-online#1191]
On chrome on Mac OSX 10.15, selecting subplots and trying to assign data values to them notifies the user that no subplots are selected despite them being selected.

This bug didn't occur about a week ago, but logged into CEO today and it started happening.

<img width="1011" alt="bug" src="https://user-images.githubusercontent.com/32107148/114773029-8632b200-9d3c-11eb-927c-95243e8d5e35.png">

**Comment by sirmspencer** [comment]
What project number is this?

**Comment by JohnMBrandt** [comment]
Hi Spencer --

It's for project 21740, though it seems to be affecting all projects under the organization. It doesn't matter if it is a newly created project like 21740 or an older project that had some plots still to be labeled. Currently this bug breaks the functionality of CEO, since the popup message notifying the user to select a sample will not go away.

Another (slightly unrelated) bug that I've noticed is that if an institution has imagery with an expired access token (such as Digital Globe), and the imagery is added to a project when the access token is valid, when the access token expires the project becomes inaccessible, as the popup notifying the user that the access token has expired repeatedly comes up after clicking "ok".

**Comment by sirmspencer** [comment]
Thank you for the report.  I have deployed a fix.  Can you please let me know if you still have issues.
