### ISSUE TITLE
Project Management - Sample Values

### ISSUE THREAD

**Issue by jesstclark** [openforis/collect-earth-online#125]
It would be helpful if, during project set-up, the user could undo or delete erroneous sample values. For example, during my first time, I accidentally entered "Forest" as a sample value, rather than what I meant, which was "Land Cover." Unfortunately, I can't seem to delete "Sample Value: Forest" from the options, which impacts whether the project thinks I'm done with a plot or not (I can't save assignments until all sample value groups have been satisfied).

**Comment by sirmspencer** [comment]
The UI has been updated significantly since this issue was posted.  During project creation you can easily add or remove answer to be answered later.  During collection, you can highlight any samples and change your answer.
