### ISSUE TITLE
Project Management - Delete Projects

### ISSUE THREAD

**Issue by jesstclark** [openforis/collect-earth-online#126]
Can users delete projects they build? I made a test project but can't delete it, only close or archive. It was clearly a test and doesn't need to persist.

**Comment by lambdatronic** [comment]
Hi Jess,

Archiving a project is equivalent to deleting it. It will no longer appear anywhere on the site. Periodically, we wipe any archived projects from our database that were archived at least a month previously. If you accidentally archive a project, just send us a message, and we can re-open it for you on the site provided it hasn't been wiped yet.
