### ISSUE TITLE
Allowing for one sample per plot in the center

### ISSUE THREAD

**Issue by KMarkert** [openforis/collect-earth-online#129]
I am trying to classify Landsat pixels and assign just one value (30 meter plots with one sample); however, the samples seem to start from a plot corner. Can we please add functionality to add just one sample per plot in the center on the project design page?

**Comment by snasaio** [comment]
As a temporary way to accomplish this, you can select gridded samples, and set the sample resolution to a value much greater than the size of the plot shape.

**Comment by lambdatronic** [comment]
Was this ever resolved? The random and gridded sample distribution options should default to placing one point in the center of the plot.
