### ISSUE TITLE
Importing/Exporting Classification Scheme for projects

### ISSUE THREAD

**Issue by KMarkert** [openforis/collect-earth-online#130]
I am using the same typology for different projects and it would be great if we can export the classes and colors to import into other projects.

**Comment by sirmspencer** [comment]
The problem with importing large classification schemes is the endless ways a user can create data that does not conform to the specification. Im going to close this issue for that reason.  If using the project level template selector is not sufficient, I would suggest opening a new issue to allow page specific template loading.
