### ISSUE TITLE
Home Page Design Issue

### ISSUE THREAD

**Issue by billyz313** [openforis/collect-earth-online#132]
There are a few design issues with the home page that should be corrected.

1. The map starts zoomed out too far and doesn't fill the height of the map panel (see attached 1.png)
2. When zoomed in the map still doesn't fill the map area, there is a space at the bottom (see attached 2.png)
3. Institution names that are long run through the info button and look bad, please limit the width and cut the text with css text-overflow: ellipsis; (also seen in 2.png)
4. Institution list panel needs to be set to the view port height and have scroll applied to it rather than the current method that allows it to continue expanding the page and having the entire page scroll instead of just that div.  (see attached 3.png)

![1](https://user-images.githubusercontent.com/1868821/39708087-d5aa5874-51db-11e8-84e5-ef79f3a90313.png)
![2](https://user-images.githubusercontent.com/1868821/39708089-d5d59d18-51db-11e8-9943-4883b9f5d486.png)
![3](https://user-images.githubusercontent.com/1868821/39708090-d5fc0656-51db-11e8-999a-3464293eb756.png)

**Comment by sirmspencer** [comment]
These issues have been fixed
