### ISSUE TITLE
Duplicate samples in projects with dense points and spatial distribution set to centered

### ISSUE THREAD

**Issue by ivanzvonkov** [openforis/collect-earth-online#1339]
## Current behavior
I created a CEO project with the following settings:
> AOI Boundary:
> - North: 14.895
> - West: 36.45
> - East: 40.00
> - South: 12.25
> 
> Plot Design:
> - Spatial Distribution: random
> - Number of plots: 1200 plots
> - Plot shape: square
> - Plot size: 1000m
> 
> Sample Design:
> - Spatial Distribution: center
> - Samples per plot: 1 / plot

And the resulting sample had 314 duplicate points.

Leaving all other parameters the same and changing
> - Spatial Distribution: random

Resulted in only one duplicate.

## Expected behavior
- Zero duplicates in all generated samples.

Let me know if I am missing something!

**Comment by sirmspencer** [comment]
What project is this?

**Comment by ivanzvonkov** [comment]
@sirmspencer 
We specifically need random distribution, I don't think using gridded with spacing would achieve that, right?
Our current short-term fix is changing the `Spatial Distribution` to `random` then there are few or no duplicates. 
Lots of duplicates only happen when `center` is used.
Is this a bug?

**Comment by ivanzvonkov** [comment]
@sirmspencer any update on this?

**Comment by sirmspencer** [comment]
> @sirmspencer any update on this?

Its in the queue to be fixed.  If its fixable, its likely 2 weeks before its deployed.
