### ISSUE TITLE
Not SERVIR institution. Alternate WMS?

### ISSUE THREAD

**Issue by sheastob** [openforis/collect-earth-online#138]
Just started trying to learn how to use CEO. I am not affiliated with a SERVIR institution. What free WMS is suggested instead that is similar to DigitalGlobe? Trying to get NDVI.

**Comment by lambdatronic** [comment]
DigitalGlobeRecentImagery, DigitalGlobeRecentImagery+Streets, BingAerial, BingAerialWithLabels, and PlanetGlobalMosaic are all publicly available imagery layers that are available to all users. The Planet layer has monthly temporal snapshots starting in January 2016 and running to present. If you want to see a computed layer (i.e., anything other than raw satellite imagery), you will need to configure the GeoDash for your project (see the button on the project creation page). You can use this feature to extract additional map and chart data from Google Earth Engine.
