### ISSUE TITLE
LOST INSTITUTION DATA

### ISSUE THREAD

**Issue by rctosnmb** [openforis/collect-earth-online#1387]
I was working in my Institution "MINISTERIO DEL AMBIENTE Y AGUA" in Ecuador, i was submiting raster archives and i deleted all the Institution with all the projects. I need to recover this information as soon as possible. Would you help me please.

Carolina Tapia O.

**Comment by rctosnmb** [comment]
Some other people was working in the same institution and they can work now but when we close CEO we can't open our Institution again

**Comment by sirmspencer** [comment]
This is restored.
