### ISSUE TITLE
Labeled data loss after CEO came back online

### ISSUE THREAD

**Issue by hannah-rae** [openforis/collect-earth-online#1388]
The last two days we (the NASA Harvest organization) were unable to access CEO due to a variety of errors including connection errors and authentication issues on the CEO side (see below image as an example authentication error). When the service came back online today, we saw extensive data loss in in-progress projects. On at least two projects we lost hundreds of labels that we are certain we completed. One project I personally finished had 100% completion of 600 points, yet when the service came back online today it says that 74% of these points are unanalyzed (luckily I had already downloaded the plots for that particular project). This is extremely saddening because we put so much time into these projects and are working on a very high priority project in Tigray. Please let us know if there is any way to recover the lost data. 

![image](https://user-images.githubusercontent.com/6354180/142952111-67c77aa8-c961-4c26-98e7-b6319f24344a.png)

**Comment by sirmspencer** [comment]
Unfortunately there is no way to recover this data.  We were not aware of anyone working this weekend and the data loss is not reversable.
