### ISSUE TITLE
Samples outside of defined northern boundary line

### ISSUE THREAD

**Issue by ivanzvonkov** [openforis/collect-earth-online#1393]
## Current behavior
I created a CEO project with the following settings:
> AOI Boundary:
> - North: 14.895
> - West: 36.45
> - East: 40.00
> - South: 12.25
> 
> Plot Design:
> - Spatial Distribution: random
> - Number of plots: 1200 plots
> - Plot shape: square
> - Plot size: 1000m
> 
> Sample Design:
> - Spatial Distribution: center
> - Samples per plot: 1 / plot

And the resulting sample had several points outside of the northern boundary line.

The same behavior is observed with spatial distribution set to random.

![image](https://user-images.githubusercontent.com/25067660/143955726-300dfc58-5015-4d85-b427-464c47088e15.png)

Link to project: https://collect.earth/collection?projectId=25768

## Expected behavior
- All samples should be inside defined boundary lines.

Let me know if I am missing something!

**Comment by sirmspencer** [comment]
Thanks for the report, we will look into it.

**Comment by sirmspencer** [comment]
Do you have a project number for this example?

**Comment by sirmspencer** [comment]
This should also be fixed.  Allow for 2 week for deployment.
