### ISSUE TITLE
"Error in update project: NULL" 

### ISSUE THREAD

**Issue by aarquero** [openforis/collect-earth-online#1394]
Dear all, 

I recently created several projects for collect landcover data, on MINAMB Institution, and I would like, please, report several bugs since one week, when we try to set our project parameters. 

Issue 1 : 
Last week [including today] I created several projects. When I try to update some parameters, CEO tell me the update is not working, "Error in update project: NULL" . My tip, it's create a new project based on the draft project,  changing my parameters, and then clicking on "create project". 
Any clues on why we can't update the project ? The modifications that I tried to do is: add a new survey card, changes the sampling, changes the % of plots assigned by users... not a big deal. 

Thanks for support,
Amelie

**Comment by sirmspencer** [comment]
That should not happen.  Which project are you using as the template?

**Comment by sirmspencer** [comment]
Hearing nothing, this issue is closed.  If it happens again, please mark which project you used as a template and do not delete it.
