### ISSUE TITLE
"error retrieving the project, see console for details".

### ISSUE THREAD

**Issue by aarquero** [openforis/collect-earth-online#1395]
Dear all, 

I recently created several projects for collect landcover data, on MINAMB Institution, and I would like, please, report several bugs since one week, when we try to set our project parameters. 

Issue 2 : 
Many many times, these last recent times, when I'm working on CEO, I have this message "error retrieving the project, see console for details". Presently, I can"t collect data to check if all is ok on the project 27176. It's not the first time, and I used to make a refresh, or log out/log in, sometimes is working, sometimes is not. 
Any clues on it ? 

Thanks for support, 
Amelie

**Comment by sirmspencer** [comment]
I cant see what happening because you deleted the project.  Please post again if you have a new project with the issue, and dont delete it.

**Comment by sirmspencer** [comment]
Hearing nothing this issue is closed.  If it happens again please note which project is the issue and do not delete it.
