### ISSUE TITLE
draw bar to no scroll mouse or large list / alphabetic sorting of institutions?

### ISSUE THREAD

**Issue by kangerluk** [openforis/collect-earth-online#149]
This comment is not a functional issue, just an improvement suggestion:
When wanting to access an institution lower located on the left panel, one needs either a mouse with scroll wheel, or click on one institution and push the down-arrow for a while to get to a lower-listed institution.
If there would be a slider bar to just pull down, that would make it easier.
Also, I wonder if it would be helpful to have the institutions listed alphabetically? The list is by now so large that it takes a while to find a specific institution.

Best,
Lena

**Comment by snasaio** [comment]
It looks like an attempt was made to add this feature, however the current implementation is not functioning correctly.  The scroll bar does not respond to a mouse click, and instead the institution panel will hide as if the hide arrow was selected.

**Comment by sirmspencer** [comment]
This functionality has been added in PR #189.  While the scroll bar has been added previously, it was covered by a div from from the hide button.  Sorting by name (new) or number of projects (old) was added.
