### ISSUE TITLE
Archived projects

### ISSUE THREAD

**Issue by wenjieji86** [openforis/collect-earth-online#150]
Hello,

Is there a way to retrieve archived/closed projects? Thanks.

**Comment by lambdatronic** [comment]
Hi wenjieji86. Not through the CEO web interface.

A closed project is still visible to admins of the institution to which the project belongs.
An archived project is effectively deleted.

I can attempt to unarchive a project from the database if you know the institution and name of the project.

**Comment by wenjieji86** [comment]
Hi Gary,

Thanks for the speedy reply. Our institution name is NMSU_test and the
projects names are "training2_olivia" and "training2_shellby".

Thank you for your help.

Wenjie

**Comment by cwadeross** [comment]
Hi Gary, were you able to retrieve the archive? 
-Wade

**Comment by tariqbfd** [comment]
Hi Gary,
My project id 1499. I am also want to retrieve the project.
