### ISSUE TITLE
Gridded sample not working properly

### ISSUE THREAD

**Issue by wenjieji86** [openforis/collect-earth-online#153]
Hi,

We were trying to create a new project with our own csv file as plot centers. Within each plot we were trying to do a gridded sample. We set the plot size as 80 meters and the sample space as 10 meters. Usually we would end up with 81 regularly gridded samples in each of our plots. But now we only have 1 sample in each plot.
We tried again without our own csv file when creating a new project, instead we did 100 random plots within a polygon we drew. And again we used 80 meters as plot size and 10 meters and sample spacing and it worked. 
So we are wondering if this has something to do with the csv file since we noticed that a plotid field is required which wasn't in the previous version of collect earth online.

Thanks for your help.

Wenjie

**Comment by lambdatronic** [comment]
I think this was already fixed awhile ago, but someone should verify that Plot Distribution = CSV and Sample Distribution = Gridded works correctly.
