### ISSUE TITLE
Track time spent filling out collection on each plot

### ISSUE THREAD

**Issue by KMarkert** [openforis/collect-earth-online#157]
Would it be possible to add a 'begin' and 'end' time stamp to output file, to track when a user started classifying a plot, and when they finished the plot? 

This should be some timer on the backend that the user doesn't have to see.

**Comment by snasaio** [comment]
Functionality added to postres server in #160

**Comment by snasaio** [comment]
This appears to be a duplicate of #152

**Comment by sirmspencer** [comment]
This functionality has been merged into master
