### ISSUE TITLE
Actually a question: is it possible to access planet basemaps (licensed) in CEO?

### ISSUE THREAD

**Issue by ricds** [openforis/collect-earth-online#1662]
Hi Devs!

For NICFI, it loads in the imagery automatically since it is free and openly available.

For Planet Licensed monthly basemaps data, is there is a way to add it as other imagery? I see there is an option for Planet Month which has the API key field, I tried that using the api key I have from my company, but it did show any image in geodash when i added that.

Is the visualization of planet basemaps possible within CEO, and what am I doing wrong - Can you advise me?

PS: if there is a better platform to ask such questions, let me know.

Thanks

Ricardo

**Comment by a-luz** [comment]
Hi Ricardo,

Yes it is possible to use Planet imagery, both on geodash and on the data collection page. Which geodash widget were you trying to create to use Planet Imagery?

**Comment by ricds** [comment]
I don’t remember which one. I just tried today again and could not find the same screen I used the other day, which said something like ‘Planet Month’.

Which widget should I use to display Licensed Planet Basemaps using the API key I have ? I would like to show some monthly maps over the USA.

Ricardo

**Comment by a-luz** [comment]
Hi Ricardo,

You could create a `Institution Imagery` widget or maybe the `Dual Imagery` widget as well to use Planet maps on the geodash  board

**Comment by ricds** [comment]
I tried adding institution imagery, Planet Monthly, select year 2020, month 6, add the API key, add this to the geodash, it did not show any image.

https://app.collect.earth/review-project?projectId=37778

**Comment by a-luz** [comment]
I'm investigating what might be the problem with this image and I'll get back to you as soon as possible
