### ISSUE TITLE
bug: samples went missing

### ISSUE THREAD

**Issue by ricds** [openforis/collect-earth-online#1681]
Hi, I noticed in some of our recent data collection with multiple interpreters at the same time, that some samples went missing in some projects. One example is this one: https://app.collect.earth/project-dashboard?projectId=38366

It has 6000 total samples, no flagged sample, no unanalyzed sample, but only 5936 analyzed samples. Thus, 64 went missing.

**Comment by a-luz** [comment]
Thanks for the information @ricds , we'll be investigating this issue in the next sprint
