### ISSUE TITLE
bug: negative sec/plot in project dashboard for some user

### ISSUE THREAD

**Issue by ricds** [openforis/collect-earth-online#1682]
Hi, I noticed in some of our recent data collection that one of our interpreters kept having negative sec/plot in the project dashboard. One example is this one: https://app.collect.earth/project-dashboard?projectId=38366

Person #5 in the list had 659 plots completed with -206.18 secs/plot. I asked the person about this, how were they collecting, what could have happened, they mention that they would leave the screen open to leave the computer and do something else, and then after a while would come back to collect. Maybe that is useful information for you.

**Comment by a-luz** [comment]
Thanks for the information @ricds , we'll be investigating this issue on the next sprint
