### ISSUE TITLE
Privacy issues (e-mails of memebers of institutions exposed publicly)

### ISSUE THREAD

**Issue by herrtunante** [openforis/collect-earth-online#170]
When opening an institution I can see the e-mails of all of the members of tjhe institution.

This seems to me to be a privacy issue as the website could be used to harvest emails and generally we should not show this information to unlogged users...

Probably the emails of the members of an institution should only be visible to the administrator of the institution. If you are not maybe you could just show the number of members of the insitution and when the last member signed up.
![image](https://user-images.githubusercontent.com/4435566/50444540-421c0900-0909-11e9-9837-b13677fa219b.png)

**Comment by snasaio** [comment]
In PR #217 we hide the email list for non users
