### ISSUE TITLE
Rename legacy variables

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#172]
Postgres was set up more recently so many variables (and fields) have been updated to better match what they are now.  The JSON database is a bit harder because the old data still lives in the .json files.  Some translation functions will be needed, or an admin route to rename old data.

For instance `sample-survey` should be updated to `survey-questions` to match the new variable `survey-rules`

**Comment by sirmspencer** [comment]
If this is worth doing, it would be a good opportunity to verify consistent casing sending and receiving data.  Is it intentional that the data is being sent from the UI snake case, and returned to the UI camel case?

**Comment by lambdatronic** [comment]
This is definitely worth doing. I'd prefer that we simply add an admin route to update the JSON database once rather than continuing to support legacy object attributes. All JSON attributes should be in camelCase both going and coming.
