### ISSUE TITLE
Bug: NICFI no longer loads using GEE asset

### ISSUE THREAD

**Issue by ricds** [openforis/collect-earth-online#1745]
This has stopped working around the week of 17-21 June, it doesnt display data in the screen anymore. It does not lists the data in the available bands which may be a hint it is not working.

The only way i figured out it works is setting the Basemap for NICFI but then i cannot build mosaics using Median of a set of dates to avoid cloud cover - which was the advantage of this feature. Can you please take a look ? this is a very important feature.

Configuration
Widget Type : Image Collection Asset
Basemap : Open Street Map
GEE asset for example : projects/planet-nicfi/assets/basemaps/asia

**Comment by a-luz** [comment]
Hi @ricds . We had an issue with some of our credentials, but it should be working now! Thanks for the report!
