### ISSUE TITLE
sentinel and landsat image collections not loading

### ISSUE THREAD

**Issue by jpardila** [openforis/collect-earth-online#181]
I created a new institution and tried to set up a few projects. In none of them, I could not manage to get the Sentinel or Landsat image collections to show. I explored projects from other users and it seems to be working right. Do I need to load those layers to my institution myself?  Are there any instructions on how to set this up?

**Comment by billyz313** [comment]
@jpardila Are you trying to add theses collections to the GEO-DASH?  If so there is a help center with instructions on adding them [https://localhost:8080/geo-dash/geodashhelp](https://localhost:8080/geo-dash/geodashhelp)
