### ISSUE TITLE
CSV and SHP upload fail

### ISSUE THREAD

**Issue by zanderVenter** [openforis/collect-earth-online#296]
Thank you for an amazing tool!

I have tried the CSV or Shapefile upload options but both seem to throw an error when I create project. 'Error retrieving the project info. See console for details.'

Here are the test cases:
CSV: https://collect.earth/collection/1820
Shapefile: https://collect.earth/collection/1821

Attaching the ZIP shapefile as well. Thank you for the help.

[bee_habitat_sample.zip](https://github.com/openforis/collect-earth-online/files/3206582/bee_habitat_sample.zip)

**Comment by sirmspencer** [comment]
SHP files require both a plot and sample file.  Could you please provide both?

**Comment by zanderVenter** [comment]
Ok I did not know that. I have now tried using both plot and sample file and it still seems to fail. I am attaching the files here. Used to try make this project. https://collect.earth/collection/1937
[buffer.zip](https://github.com/openforis/collect-earth-online/files/3251114/buffer.zip)
[point.zip](https://github.com/openforis/collect-earth-online/files/3251115/point.zip)

**Comment by sirmspencer** [comment]
It looks like your samples are missing "sampleid"

**Comment by sirmspencer** [comment]
The newest release will give you better feed back and prevent bad projects to be created.
