### ISSUE TITLE
Allow users to set gamma values in Image Parameters for Image Asset

### ISSUE THREAD

**Issue by mnahmad** [openforis/collect-earth-online#330]
I have an Image asset from GEE, on GEE I can set gamma values to control brightness of the image. If I use the same asset in Collect Earth Online, I am not allowed to use the gamma values thus the image looks a bit dark. 

Is there a way to set the gamma values for Image asses for example 

{"bands":"B4,B3,B2","min":"0,0,0","max":"1500,1500,1500", "gamma": "2"}

If not, please allow users to set gamma values in Image parameters for Image asset.

Thanks

**Comment by KMarkert** [comment]
Hi @mnahmad, you should be able to set the gamma value for an asset using the same syntax as on GEE. Can you try setting the gamma value to an integer type instead of a string like this?

`{"bands":"B4,B3,B2","min":"0,0,0","max":"1500,1500,1500", "gamma": 2}`

**Comment by billyz313** [comment]
Hi @mnahmad, 
I was able to create an image asset widget with the exact parameters you show.  Can you please link me to the specific Geo-Dash you are working with so I can debug?

**Comment by mnahmad** [comment]
Hi @KMarkert, thanks for the response. I tried but it did not work for me. 

Hi @billyz313 again thanks for the response and offer to help. Do you want me to add you as admin to our organization or you just want to know the name of my origination and project.

**Comment by billyz313** [comment]
@mnahmad you should be able to go to your projects collection page and click "Go to first plot" and a Geo-Dash will open in a new tab.  In the Geo-Dash tab you can copy the link and paste it here, or skype it to me @ billyz313 whichever you prefer.

**Comment by mnahmad** [comment]
@billyz313 thanks for helping. Below is the link 

https://collect.earth/geo-dash?institution=474&pid=2451&plotid=134764412&plotshape=circle&aoi=%5B-15.225908332120131%2C13.493608501960338%2C-15.22315906787987%2C13.49519165541524%5D&daterange=&bcenter={%22type%22:%22Point%22,%22coordinates%22:[-15.2245337,13.49440008]}&bradius=17.84

**Comment by billyz313** [comment]
@mnahmad I was able to create widgets with the image assets you had on that Geo-Dash both with, and without the gamma set.  I did find a bug with the cache logic of the assets that i fixed and will be released to the server in the next push.  Each image assets was being cashed, but if a second widget was setup with the same asset and different visParams the cache was ignoring the new visParams and just giving the cached version which would have the original visParams.

Here is the exact params I set with your assets:

`{"bands":"B4_median,B3_median,B2_median","min":"0","max":"5000","gamma":"2"}`

**Comment by mnahmad** [comment]
@billyz313 thanks for quick response and help. 

That explains the issue. I created multiple widgets of the same asset (in two different projects) to see if I can set the gamma values.

**Comment by billyz313** [comment]
@mnahmad if you would like to manually clear the cache while waiting for the code to be pushed to the server u can open a browser console window and type
`localStorage.clear()`
You will have to clear the storage manually for each project, else it will still just take the first one to cache.  The fix has been merged to the master branch and is just awaiting deployment, once deployed you won't have to worry about manually clearing it as it will also compare the params that are set while caching.

**Comment by mnahmad** [comment]
@billyz313 localStorage.clear() worked. Thanks for the quick solution.
