### ISSUE TITLE
CSV file upload fail when creating a project

### ISSUE THREAD

**Issue by beckyjpm** [openforis/collect-earth-online#337]
[AS_PLOT-learing-DOS.zip](https://github.com/openforis/collect-earth-online/files/3374161/AS_PLOT-learing-DOS.zip)
I uploaded a CSV file of plot location under Plot design. The collect earth says: " Error creating project" and "Malformed plot CSV.Fields must be LON,LAT, PLOTID." My CSV document has three columns and columns' name are LON,LAT and PLOTID. Could you give me any suggestions that why this error shows up? Thanks!

**Comment by sirmspencer** [comment]
They must also be in the order listed.

**Comment by beckyjpm** [comment]
what do you mean for order listed? Do you mean that sorts from small PLOTID to large PLOTID? I ordered the sheet with PLOTID, but it still shows the same error message.

**Comment by KMarkert** [comment]
@beckyjpm Can you share a simplified version of the CSV you are trying to create a project with? That can help us debug.

**Comment by beckyjpm** [comment]
[AS_PLOT-learing-DOS.zip](https://github.com/openforis/collect-earth-online/files/3374848/AS_PLOT-learing-DOS.zip)
I attached a simplified version here. Thanks for help.

**Comment by KMarkert** [comment]
@beckyjpm just had a look at the CSV you provided. It seems like there are a two formatting errors that are causing CEO to fail on the project creation

1. The `PLOTID` field needs to have unique values. It seems like there are some repeating values in the column (196000000000000 for example).
2. The column order needs to be `LON`, `LAT`, and then `PLOTID` like the example shows. CEO searches the CSV in that order and will fail when the columns are in any other order.

As an example, a table formatted this way should work:

| LON  |  LAT |  PLOTID | 
|------|------|---------|
|  -170.72925 | -14.29135  | 0 |
| -170.700988  | -14.275058  | 1  | 
| -170.704073  |  -14.306996 |  2 |

**Comment by sirmspencer** [comment]
Thank you @KMarkert for clarifying.

**Comment by sirmspencer** [comment]
Your plotId numbers are also too large, the largest number supported is 2,147,483,647

**Comment by beckyjpm** [comment]
Many thanks @sirmspencer @KMarkert
