### ISSUE TITLE
Clean up geo-dash.ftl

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#349]
geo-dash.ftl:
Lines 9-27: Why is this Javascript code in the FTL file rather than in geo-dash.js?
Line 9: let -> const
Line 10: var -> const (don't we already call this.getParameterByName("projectId") in geo-dash.js?)
Line 11: This function needs to be rewritten to use const, ?:, and not overwrite the input arguments to the function (impure).

**Comment by sirmspencer** [comment]
The vars on 9, 10 dont look like they are being used.

Is this function still needed or is it done in the geo-dash.js file?

**Comment by billyz313** [comment]
@sirmspencer None of that is needed, it was legacy code from pre-react time.  It is now removed in PR #359
