### ISSUE TITLE
Accuracy Assessment

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#35]
I've been working with the mapcha/CEO projects this week. I'm currently working in R to merge our predicted values based on lat/long and then running the confusion/error matrices.

It would be great to consider adding this process as a new feature: when we upload the csv with lat long (or a shapefile) to specify our sample locations, could we also preserve the predicted class and unique ID? Then include this info in the spreadsheet download as well? It would be pretty cool to also have the confusion/error matrices calculated in mapcha (with the ability to insert new columns for new prediction results since model building is an iterative process). 

The algorithm is the traditional users vs producers accuracy. To get overall accuracy, we'd need to be able to specify sample weights if we were working with a stratified random sample.

**Comment by lecrabe** [comment]
Hi

Thanks for the message. This is definitely something we should have implemented in CEO, or connected at least to the existing.

At the moment, we have these functionalities already set-up in the accuracy assessment design: 
- calculate areas from the map for each strata, 
- generate the stratified random sample 
- create a CE (not O) file to perform the validation

And in the accuracy assessment analysis :
- the map class (predicted class) are kept in the file 
- they are compared to the reference data
- the calculations of confusion matrix, UA, PA, stratified area estimates and confidence intervals are created using the weights of the strata 

Happy to discuss how to plug those existing features into CEO.
Best
Remi

**Comment by sirmspencer** [comment]
The output files now include the original unique ids provided by the csv or shp file.
