### ISSUE TITLE
Allow Geo-Dash created imagery to be added to a project

### ISSUE THREAD

**Issue by billyz313** [openforis/collect-earth-online#361]
Currently Geo-Dash created imagery by default is just added to the widget, but has the option to add to the institution.  This issue will extend the functionality to a radio button collection:

 (X) Add to widget (Default selected)
 (  ) Add to project collection basemaps
 (  ) Add to institution basemaps

These options will cascade up.

**Comment by sirmspencer** [comment]
I think this is complete now that we redirect users to create the imagery at the institution level.
