### ISSUE TITLE
SRS Mismatch Between Uploaded Shapefile and Project Map

### ISSUE THREAD

**Issue by tertiarymatt** [openforis/collect-earth-online#376]
In project creation, uploading shapefiles appears to require that they be in a Lat/Long form (WGS84 works). This applies both to plot locations and to point locations.

However, the map displayed in the data collection interface appears to use Web Mercator, so circular points that were uploaded as a shapefile tend to become ellipses when displayed.

**Comment by tertiarymatt** [comment]
[For an example, see this project.](https://collect.earth/collection?projectId=5352)

**Comment by biplovbhandari** [comment]
Hi, @tertiarymatt I cannot access the project. Can you share the shapefile, please?

**Comment by tertiarymatt** [comment]
Hi there Biplov. Sorry for the delay, I didn't see the email in my inbox. 

I've updated the project to be available to any logged in user. Should have access now.

**Comment by biplovbhandari** [comment]
Hi @tertiarymatt Looks like there is a bug in there as well. I still cannot seem to access the project. Maybe you have to add me to the organization. Can you add biplov.b@adpc.net to your org? Also could you share me the shapefile in the same email above so I can replicate in my local machine? Thanks!

**Comment by tertiarymatt** [comment]
Done. You should receive two emails from my USDA email.

**Comment by sirmspencer** [comment]
This is not a bug. @tertiarymatt If you were able to upload the shape file already projected to Web Mercator, would that eliminate the re-projection distortion? You can also upload the data as a csv file with only the center defined, then openlayers will draw a circle in the web view port.
