### ISSUE TITLE
Create an offline workflow for data collection using PDFs and spreadsheets

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#380]
:Develop an option to download annual time series image chips as pdf documents for regions with slow or intermittent wifi connections | Example code to build from provided by Remi Dannunzio, FAO, https://github.com/openforis/accuracy-assessment/tree/master/Rscripts/annual_time_series

Is there an option to save records while offline that then upload to the cloud once wifi signal is back. For example, you can set this up in google docs and ground odk does this too. can we mimik with CEO data records?

The informatics download as pdf is already figured out by Remi at FAO, we just need to update and translate his code for CEO.

**Comment by sirmspencer** [comment]
This needs a few more pieces to work.  The sequential way we get plots means user could end up duplicating work.  We need to implement assignments or random plot assignments before this.

**Comment by lambdatronic** [comment]
CEO native data collection should be done using collect.earth or with a no-internet Raspberry Pi CEO instance.

This issue should be focused on building a PDF generator for the Geodash widgets associated with any given project. The project administrator should be able to use this to download a set of PDFs (or one large multi-page PDF) with the pre-rendered Geodash widget images for each plot (with each page labeled by project name and plot id). The data collector would then reference these PDFs on their desktops or via a stack of print-outs while answering the survey questions in their browser on CEO's (otherwise unchanged) Collection page.

**Comment by lambdatronic** [comment]
Since it may take quite some time to automatically render every Geodash widget for every plot via a sequence of gee-gateway calls, the user experience may be improved by sending the project admin an email with the generated PDF(s) when the computation has completed.
