### ISSUE TITLE
Add mailing list functionality

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#386]
Add a new page that is only accessible to admin@openforis.org.

On this page, there should be two form fields (Subject and Body) as
well as a button labeled "Send to All CEO Users".

Pushing this button should send a mass email to all registered users
(i.e., everyone with an email address in the `users` table).

**Comment by rfontanarosa** [comment]
/mailing-list isn't accessible from other pages.

advanced functionalities of CKEditor need to be configured.
