### ISSUE TITLE
add a geodash default template that mirrors the Collect Earth desktop GEE windows.

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#392]
From Alfsonso:
Here is the script that we use now as default for Collect Earth and that is published as a GEE App so it does not require to sign-in to GEE

The code for the script ( it uses the new ui.url.get method ) is here :  https://code.earthengine.google.com/?scriptPath=users%2Fsanchezpauspro%2FApps%3ACollectEarthPlotAncillary

The GEE App results on this (see how the polygon is passed as a parameter): https://collectearth.users.earthengine.app/view/plot#geoJson={%22type%22:%22MultiLineString%22,%22coordinates%22:[[[100.0,%200.0],[101.0,%201.0]],[[102.0,2.0],[103.0,3.0]]]}

Here is how to publish apps if you haven’t done it before: https://developers.google.com/earth-engine/apps

The script refers to this other script that actually does most of the work: https://code.earthengine.google.com/?scriptPath=users%2Fcollectearth%2Fce_scripts%3Aframes_landsat_v4

The script refers to this repository: https://code.earthengine.google.com/?accept_repo=users/collectearth/ce_scripts

If you are going to use the same approach it would be better if you create your own GEE App so we do not overload the one used in Collect Earth, there is a limit to the number of requests although I am not sure yet if this is a problem or not but better safe than sorry.

**Comment by billyz313** [comment]
This feature has been handled by issue #449 which adds the ability to include it.
