### ISSUE TITLE
Allow reclassifying flagged plots on Collection page

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#395]
Currently, there is a bug in the Collection page (may be in
collection.js or in JsonProjects.java + PostgresProjects.java) that
prevents users from assigning new values to a previously flagged plot. The current UI allows users to browse back to their previously analyzed plots (including flagged plots) and assign new values to their samples. However, if a plot has been flagged, these new values are ignored and are not saved in the database. This needs to be fixed.

If a previously flagged plot has new values assigned to its samples,
then these values should be saved to the database, and the flagged
attribute should be set to false.

**Comment by sirmspencer** [comment]
This is related to #355

**Comment by rfontanarosa** [comment]
I've found the issue.

When we flag a plot clicking on the FLAG button and calling the function **flag_plot**, it creates a new record inside the **user_plots** table.

On the other hand, when a plot is saved using SAVE button, two rows are created on the db by the function **add_user_samples**: one in **user_plots**, the other in **sample_values**.

BUT if try to review a previously analyzed plot calling the function **update_user_samples**, it doesn't check if the plot is flagged or saved so it tries to update a record that not exists in the table **sample_values**.

What I did if add a check which UPDATE in case the record exists and INSERT if it doesn't.
At the same time, when an analyzed record is flagged that record should be REMOVED.

With this solution there is only a small bug in the front-end part that occurs when the user flag a previously analyzed plot and that record is the last one.

**Comment by lambdatronic** [comment]
Good work. How do you intend to solve the UI bug?

**Comment by rfontanarosa** [comment]
I've just added a check to disable FLAG PLOT button in case the plot is flagged.
There's still an issue when the last plot is analyzed: it shows a popup alert without update the interface.
