### ISSUE TITLE
Allow users to edit their institution's imagery sources (and make sure they appear on the Review Project page)

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#398]
There is no way to edit the imagery source. The process of adding WMS services is very error prone (e.g. mistyping the JSON parameters or changing the resolution or format) so you should be able to edit the imagery sources (maybe the base ones like Bing Maps or Digital Globe should be " locked" )
http://i.imgur.com/0jW6gaw.png

When I choose the PNOA as a basemap it works fine assessing plots, but if I go back to the project page (using the Edit button) the basemap parameter appears empty, even though PNOA is in the list of avaliable sources. see images.

http://i.imgur.com/zurwJEF.png
http://i.imgur.com/gPUGd6u.png

**Comment by rfontanarosa** [comment]
I've done a small tour and I've discovered that probably the second point is no longer valid: it keeps the selected imagery.

**Comment by lambdatronic** [comment]
Good to know about the second point. Good luck on the first issue (Allowing users to edit their Imagery sources on the Review Institution page).

**Comment by rfontanarosa** [comment]
I've pushed update-imagery branch which contains all the changes to make an imagery editable BUT there are some small fixes that should be discussed.

One of these is "when the imagery list is retrieved from the server it filters the results removing some attributes, like the token keys". I don't know the reason why, maybe security reason but this way when a user try to change an imagery the form will be not filled completely.

**Comment by rfontanarosa** [comment]
this is the part of the code which filters the imagery fields:

                    // Return only necessary fields for types we proxy
                    var type = sourceConfig.get("type").getAsString();
                    if (List.of("DigitalGlobe", "EarthWatch", "GeoServer").contains(type)) {
                        var cleanSource = new JsonObject();
                        cleanSource.add("type", sourceConfig.get("type"));
                        newImagery.add("sourceConfig", cleanSource);
                    } else if (type.equals("Planet")) {
                        var cleanSource = new JsonObject();
                        cleanSource.add("type",  sourceConfig.get("type"));
                        cleanSource.add("month", sourceConfig.get("month"));
                        cleanSource.add("year",  sourceConfig.get("year"));
                        newImagery.add("sourceConfig", cleanSource);
                    } else {
                        newImagery.add("sourceConfig", sourceConfig);
                    };
