### ISSUE TITLE
Update CSV instructions

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#407]
Info in project set up form: -Specify your own plot centers by uploading a CSV with these fields: LONGITUDE,LATITUDE,PLOTID.

Gives error message: Malformed plot CSV. Fields must be LON, LAT, PLOTID.

![image](https://user-images.githubusercontent.com/6980676/75175353-2a543680-5700-11ea-9915-284df39d93be.png)

**Comment by rfontanarosa** [comment]
That text and the text which describes the format of the sample CSV file need to be changed:

-Specify your own plot centers by uploading a CSV with these fields: LON,LAT,PLOTID.

-Specify your own sample points by uploading a CSV with these fields: LON,LAT,PLOTID,SAMPLEID.

**Comment by rfontanarosa** [comment]
@lambdatronic this issue should be closed.
