### ISSUE TITLE
window size & menu failure

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#421]
Reducing window size below 958 pixels kicks in adaptive site design where only the Institution list is shown. (this is also the default state for mobile)

When the adaptive site design is active, there are host of issues:
- three horizontal line menu icon does not work on any page
- right hand Plot Navigation etc. menu does not appear when in a project
- when on the index page, the map does not appear (this may be intentional)

**Comment by rfontanarosa** [comment]
missing bootstrap javascript dependency (header.ftl)
unclosing div (navbar.ftl)
consider to update jquery from 3.1.1 to 3.4.1 (there are no compatibility issues: https://blog.jquery.com/)

**Comment by rfontanarosa** [comment]
hi @kdyson, can you verify if the point 2 is still valid? because when the window is resized the plot navigation gets moved under the map:

![Schermata 2020-04-02 alle 11 20 54](https://user-images.githubusercontent.com/10047945/78232322-5bc8da80-74d4-11ea-8836-b32b5769e880.png)

**Comment by kdyson** [comment]
Ok yes the second point is as you say. On a desktop/mouse input computer, I can scroll down to see the data collection interface.

However on a mobile/touchscreen device, I cannot scroll down past the map. The map just moves.

**Comment by rfontanarosa** [comment]
Hi, thank you for your clarification. You're right. On a mobile it's impossible to scroll down and this make the collection page unusable.

I'm thinking to put a button on the top right corner of the map to toggle the collection menu because the solution can't be keep the layout as it because this is the effect on an iPhoneX:

![Schermata 2020-04-03 alle 11 00 09](https://user-images.githubusercontent.com/10047945/78342965-6fd70f80-759a-11ea-9452-e4afaefdb4c4.png)

**Comment by rfontanarosa** [comment]
Ok, probably the best way is adding a toggler for the sidebar like this:

![Schermata 2020-04-03 alle 17 34 20](https://user-images.githubusercontent.com/10047945/78379039-17236900-75d2-11ea-9b7b-6713e81828d6.png)

![Schermata 2020-04-03 alle 17 34 30](https://user-images.githubusercontent.com/10047945/78379050-1ab6f000-75d2-11ea-9172-0f85142d0a3d.png)

This is similar to SEPAL:

![Schermata 2020-04-03 alle 17 35 05](https://user-images.githubusercontent.com/10047945/78379077-25718500-75d2-11ea-9464-0cc5ae0c6f74.png)

**Comment by rfontanarosa** [comment]
Discussing with @lambdatronic we found another solution, less invasive than the one I've proposed but effective. I've added a button, visible only when the sidebar is put below the map, that allows to switch between the two sections (map and sidebar):

![Schermata 2020-04-03 alle 22 08 57](https://user-images.githubusercontent.com/10047945/78400993-10a7e800-75f8-11ea-8bd6-4820a043c71a.png)

![Schermata 2020-04-03 alle 22 09 08](https://user-images.githubusercontent.com/10047945/78400999-130a4200-75f8-11ea-814e-984023272519.png)
