### ISSUE TITLE
Pilot mode, before publishing project

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#425]
There is a need to balance the ability to test projects and be able to revise during the testing phase, but also lock down some quality control procedures once data collection begins. 

We proposed adding a 'pilot' or 'test project' button that people can use to pre-publish a project set up. This would operate the same as the publish option, where the user can have some partners test data collection and evaluate their question and answer set up. Then if they determine they'd like to revise the project (questions and answers, rules), that would be allowed. However, the revision would then clear all the test answers that were saved during this 'pre-publish' phase from the database. Finally, once a user has tested and finalized the design, they will officially publish. Once it's published it is no longer editable.

**Comment by sirmspencer** [comment]
I am splitting this into two issues
