### ISSUE TITLE
Option to delete test/demo projects 

### ISSUE THREAD

**Issue by africaf** [openforis/collect-earth-online#429]
Ability to delete projects that have not data collected or data collected is minimal and which main purpose has been for testing and/or demos

**Comment by karistenneson** [comment]
Don't we have a delete option already?

**Comment by biplovbhandari** [comment]
We do have delete options already. You can delete the project by going to the `review-project` page. You will have to `Close Project` before the `Delete Project` shows up. 

![image](https://user-images.githubusercontent.com/4207677/77141520-536caa80-6aa5-11ea-86ac-3a5d25b04c91.png)
