### ISSUE TITLE
Full TimeSync integration

### ISSUE THREAD

**Issue by africaf** [openforis/collect-earth-online#430]
Access to TimeSync features and capabilities from CEO, including collection of data.

**Comment by lambdatronic** [comment]
Review/replace these files from Yang on the fb-timesync branch:
- ts_scripts.js
- ts_specIndexStretch.js
- ts_tooltips.js
- collection.js
- timesync.js
- navbar.ftl
- timesync-dash.ftl
- timesync.ftl
- ts-chip-qa.ftl
- ts_main.ftl
- timesync_style.css: Rename to timesync.css.
- deploy/tsceo.jks: should contain "timesync" key

**Comment by sirmspencer** [comment]
We are adding the user packet portion of time sync separately.  We are eliminating "full integration"  if requested, we will open a new task to add the chips page as geodash widget.
