### ISSUE TITLE
sample limit threshold/project is currently set too low, at 200

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#432]
When creating new projects, the threshold on number of samples per project is set far too low, at just 200. Can we increase this number? I don't remember what we had it set to initially, but it was much higher.

**Comment by biplovbhandari** [comment]
@karistenneson @lambdatronic While it is true that the `Samples per plot` is limited to 200, but there is a trade-off between the `Number of plots` and `Samples per plot`. Altogether the system allows 50,000 total samples. If we were to increase the `Samples per plot` I guess we need to adjust that number as well. I want to know your thoughts before start working on it.

![image](https://user-images.githubusercontent.com/4207677/77242798-9c01a080-6c2a-11ea-8d26-f8be638e52fc.png)

![image](https://user-images.githubusercontent.com/4207677/77242800-a0c65480-6c2a-11ea-9314-585745da8deb.png)

**Comment by lambdatronic** [comment]
I believe there is a misunderstanding in this issue.

The number of plots per project is set quite high at 5000.

The number of samples per plot (i.e., dots within the plot) is set to 200.

The total number of samples (i.e., num plots * samples per plot) is 50,000.

These numbers should be sufficient for most uses. This looks like a user error.
