### ISSUE TITLE
creation of non-functional project via bounding box error

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#435]
If you click on a project under Select Project, then draw a new bounding box, then go back and select None under Select Project, the old bounding box remains and you can draw a second (see image). If you then create the project, it has no map. When you publish the project, it creates an error only, there is no project (see image). See project here: https://collect.earth/collection?projectId=6378

**Comment by biplovbhandari** [comment]
I think I understand what you are saying. Here's what I understood:

1. In the `Create Project` page, if you `Use Project Template` and select a project, it loads with the details of that project including the AOI, plots, and samples. If you just use it as is, it will work.
2. But if you go back and switch the template project to use `None`, it will give an empty map. You can still draw your AOI, fill in `Plot Design` and `Sample Design` and `Create Project`. It will create the project, but won't show the AOI or plots or samples. If you go to the collection page, it will show an error.

Some other feature in there:

3.  You can select the project template and not use that project AOI, samples, and plots by unticking `Copy Template Plots and Samples`. Then you can go ahead and draw your own AOI and fill in the `Plot Design` and `Sample Design`.

**Comment by biplovbhandari** [comment]
I just sent a PR that resolves that. In the meantime, for a workaround, try changing the Basemap source and it should work.

**Comment by kdyson** [comment]
Sounds good! Let me know when it goes & Ill test.
