### ISSUE TITLE
Weird plot distribution & no sample points in plots

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#439]
https://collect.earth/collection?projectId=6483

While testing the behavior of the sampling plot/points for the manual, I ran into some strange behavior in this project:
There are no sample plots on the right hand side of the sample area. 
There are no sample points in each sample plot.

**Comment by biplovbhandari** [comment]
What are the steps to reproduce this error?

**Comment by kdyson** [comment]
I created a project with sample plots gridded 500 m apart, 40m circles. Sample points gridded 30m.

I was testing project creation, so i just used a random bit of the ocean.
