### ISSUE TITLE
Loss of all project information when survey card order is changed.

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#442]
Clicking on the up and down arrows to change the order of survey cards catastrophically fails & displays  a blank screen. All project data is lost.

Steps to recreate this problem: 
1. Create a survey card with a parent question and multiple children questions. Might just work with a single question also.
2. Create a second survey card with a question
3. Move either card.
4. Here's the result:

![image](https://user-images.githubusercontent.com/6980290/78391398-22a76d80-759b-11ea-8dd8-f7644f534a64.png)

**Comment by sirmspencer** [comment]
I cannot reproduce this.  Can you send a screen shot of the survey questions you entered before you try to change the order?

**Comment by kdyson** [comment]
![image](https://user-images.githubusercontent.com/6980290/84228700-93d43700-aa9c-11ea-88b6-15b3c7bc4895.png)

**Comment by kdyson** [comment]
Clicking the blue up arrow on "Survey Card Number 2" successfully recreated the error.
