### ISSUE TITLE
Automating monthly image mosaics from GEE into data collection page (with temporal arrow advance)

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#446]
We are building some apps for validating near real time alerts, as part of this effort we would need to automate adding in Sentinel 1 and Sentinel 2 mosaics from GEE every month (or every other week). Can we automate adding the most recent image mosaics (on a biweekly or monthly frequency)? It would be great to add both to geodash (which I assume is the easiest) and also the data collection page. Can we then add the ability to navigate by month (or biweekly) using the temporal navigation arrow that we have for Planet (that advances by month)?

**Comment by biplovbhandari** [comment]
- [ ] Sentinel-2 Mosaic
- [ ] Sentinel-1 Mosaic
