### ISSUE TITLE
issue on commit 159b0c1: angular missing module

### ISSUE THREAD

**Issue by rfontanarosa** [openforis/collect-earth-online#47]
i tried to start the application but there is an angular error caused by geo.js 'cause it now imports an undefined module: geodashadmin.
only geo-dash.ftl includes the javascript in which is defined geodashadmin module.

i've fixed including the script also in the header.ftl but I don't know if it is ok:

<script type="text/javascript" src="${root}/js/geo-dash-admin.js"></script>

:)

**Comment by billyz313** [comment]
Sorry about that, i had done it wrong, just including in the other ftl.  I updated the geo-dash.ftl as well to reflect the change.

**Comment by lambdatronic** [comment]
Thanks for catching that, Roberto. I fixed your fix, Billy. ;-)
