### ISSUE TITLE
Create react component for the navbar.

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#479]
- [ ] The component should accept the current page components as a child with {this.props.child}
- [ ] Use react to hide and show the collapsed menu instead of bootstrap.js
- [ ] If possible, eliminate the need for "calc(100vh - 61px)" in multiple page css. (Future development)

**Comment by rfontanarosa** [comment]
what do you mean with header? the navigation bar (navbar.ftl) or header.ftl?

**Comment by sirmspencer** [comment]
> what do you mean with header? the navigation bar (navbar.ftl) or header.ftl?

Good question. I did mean navbar

**Comment by sirmspencer** [comment]
- Create a new component file in src/main/resources/public/jsx/components called navbar.js.
- Use Create a component that will display the navbar, and then render {this.props.children}
- Pass the page component as a child like
```
<NavBar>
    <Home />
</NavBar>
```

See SideBar in collections as an example of rendering {this.props.children}

**Comment by rfontanarosa** [comment]
this issue will include the convertion of the following pages into react:

- src/main/resources/template/freemarker/support.ftl
- src/main/resources/template/freemarker/register.ftl
- src/main/resources/template/freemarker/password-reset.ftl
- src/main/resources/template/freemarker/password.ftl
- src/main/resources/template/freemarker/login.ftl
- src/main/resources/template/freemarker/geo-dash-navbar.ftl
- src/main/resources/template/freemarker/about.ftl
