### ISSUE TITLE
Allow public projects to only use public imagery and reserve institution imagery for private projects

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#527]

**Comment by sirmspencer** [comment]
With current code chages, the user will only be able to see private imagery if they are part of the project institution.  The next step will be to add warnings when creating and modifying projects.  One option is to allow the admin to have a mix if they so chose.  The other option is to enforce strict adherence to the idea that public projects should only have public imagery avalible to all users.
