### ISSUE TITLE
Migrate collect.earth to GCP server

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#528]

**Comment by sirmspencer** [comment]
This is done for the existing back end.  This will need to be updated when we create the new back end.

**Comment by sirmspencer** [comment]
- Karen :: Test all pages on ceo.sig-gis.com with the dev database
   - Matt  :: Rebase development onto master and deploy to ceo.sig-gis.com
   - Matt  :: Take down collect.earth and move the production DB to ceo.sig-gis.com
   - Jeff  :: Change DNS records for collect.earth to point to ceo.sig-gis.com and drop ceo.sig-gis.com DNS records
   - Matt  :: Retire collect.earth server
