### ISSUE TITLE
option to shuffle plots in project set up

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#536]
I'm labeling plots in a new project and it looks like all the plots with the same land cover are clustered together from when we made the stratified sample in GEE. Can we add a 'shuffle button' option to randomize plot order in project set up? This makes reviewing hard, so I am hoping there are some good ideas to keep the review process in tact.

**Comment by sirmspencer** [comment]
Shuffle will be quite difficult to implement.  What I can do is add a buffer when the points are generated so they are less likely to clump.

I also would suggest trying a gridded set.  The earth itself is not predictable, so a gridded set should have a randomness to it.

**Comment by sirmspencer** [comment]
I may have miss understood you.  Are you wanting the plot ids to be randomized?

**Comment by karistenneson** [comment]
yep, Was hoping to get an option for the user to randomize the order the plots are presented for interpretation.
