### ISSUE TITLE
Two viewers to simultaneously interpret T1, T2, and additional dates

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#553]
I believe I've added this before, but I'll reiterate that it would be useful to be able to have the ability to launch two viewers simultaneously in order to more easily compare time 1 and time 2 imagery. Ideally, the user would be able to interpret and assign LU and/or LC classes for both dates at the same time. Thinking about interpreting time 3 and above, it would be very helpful to be able to pull in the interpretations from a previous time period, along with the associated imagery in one viewer and allow the user to interpret the next time period while simultaneously viewing the historical and new imagery. If no change has occurred, it would be ideal to have a button that would allow the user to copy the LU/LC calls from the previous time period to the new time period.

**Comment by sirmspencer** [comment]
This is a duplicate issue of #396
