### ISSUE TITLE
Remove references to documentRoot

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#562]

**Comment by rfontanarosa** [comment]
- [ ] mercator.js
- [ ] collection.js
- [ ] create-institution.js
- [ ] create-project.js
- [ ] geo-dash-help.js
- [ ] geo-dash.js
- [ ] home.js
- [ ] institution-dashboard.js
- [ ] project-dashboard.js
- [ ] review-institution.js
- [ ] review-project.js
- [ ] widget-layout-editor.js

**Comment by rfontanarosa** [comment]
Hi @sirmspencer 

I was removing all documentRoot references from the files when I had an idea.

What if we move the back-end API to another server?

Maybe we can substitute it with a configuration variable (ceoApiUrl). It's easier to get (no more attributes) and the code will be ready in case we want to separate front-end and back-end.

Look here: https://stackoverflow.com/a/30602665

What do you think?

**Comment by rfontanarosa** [comment]
adding this into webpack.config.js...

```
externals: {
    Config: JSON.stringify({ apiUrl: "" }),
},
```

... and importing this from jsx files...

`import Config from "Config";`

we can use a configuration variable that doesn't need to be passed as a property.
This saves a lot of pain and it could be useful in the future.
