### ISSUE TITLE
Make the bar to hide the project list panel easier to see. 

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#568]
- Make the button wider
- Make the button short and centered vertically.  If it is only 2rem tall, it will stick out like a tab instead of blend in.

**Comment by rfontanarosa** [comment]
included into issue #505 there is a google drive document (https://drive.google.com/file/d/1JAAq5o6VVeA85_btfnrZfC7kmxUbPlRg/view) that describes how that menu should be modified (see slide 5 and 6). should I use that example?

**Comment by rfontanarosa** [comment]
ok, I've make it wider and centered. but I'm not sure that this is what you are expecting...

https://github.com/openforis/collect-earth-online/compare/rfontanarosa_project-list-bar

![Schermata 2020-07-15 alle 13 41 48](https://user-images.githubusercontent.com/10047945/87543320-cfb67980-c6a4-11ea-8504-4cc3ed12379a.png)
