### ISSUE TITLE
Use the npm version of Highcharts instead of directly importing the JS.

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#592]

**Comment by rfontanarosa** [comment]
node_modules is not under public folder so simply adding highcharts dependency into package.json is not enough.

in my opinion the best way is https://github.com/highcharts/highcharts-react.

**Comment by biplovbhandari** [comment]
yes, I am aware of that. I am working on getting the same.

**Comment by sirmspencer** [comment]
This is done
