### ISSUE TITLE
Sample color for color blind people

### ISSUE THREAD

**Issue by KMarkert** [openforis/collect-earth-online#60]
Hard to see the red sample locations on some green imagery. Maybe change the color that can be easier to see.

**Comment by herrtunante** [comment]
We should use yellow as the color in the plot boundaries and dots (as it is more visible than white and works even in snow covered areas)

**Comment by sirmspencer** [comment]
The plot and project boundaries are yellow.  The sample colors for un assigned samples are either white or black.  At this point it is up to the survey designer to use appropriate colors.
