### ISSUE TITLE
Update Institution component on home page

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#607]
- [x] Replace the unicode info icon with the text "visit"
- [x] Add the down icon the the far left side for each institution 
- [x] Add very slight border between each row

**Comment by rfontanarosa** [comment]
Do you have an example of how the VISIT button should be?

The down/right icon will be visible only if the institution has at least one project 

Is 0.25rem enough? (see the attached image)

![Schermata 2020-07-27 alle 17 16 05](https://user-images.githubusercontent.com/10047945/88559490-2ae55600-d02d-11ea-8847-4a5acc070292.png)

**Comment by sirmspencer** [comment]
The middle visit button looks good.  What are you referencing with .25rem?

**Comment by rfontanarosa** [comment]
The middle VISIT button style is hover. Maybe I can use the following style:

![Schermata 2020-07-27 alle 20 15 16](https://user-images.githubusercontent.com/10047945/88576606-fcc04000-d045-11ea-9735-0823f4db5e72.png)

With .25rem I mean the space between "blablabla" and "prova".

**Comment by sirmspencer** [comment]
That button looks good.  Between institutions you only need to add 1 or 2 pixels.
