### ISSUE TITLE
When we archive or hide an imagery, nothing is updated in the widgets

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#626]
Is this ok?  
1. Should this be handled in geodash if no imagery is returned?
2. Do we need to remove or reset the imagery in the widgets when they are removed?

**Comment by billyz313** [comment]
Yes, I think if the imagery the widget is looking for no longer exists we should reset it to the default imagery.

**Comment by sirmspencer** [comment]
Ask Valeria for institutions to convert widget base maps to OSM.
