### ISSUE TITLE
Improve the user experience when analyzing plots - Mouse actions & shortcuts

### ISSUE THREAD

**Issue by herrtunante** [openforis/collect-earth-online#63]
When assessing a plot it would be nice if it was easier to select the points.

1. Ctrl+Left click to select all the plots within the selected rectangle (already there). It would be easier for the operator if the action would just be "Right-click" as it makes instead of having to press control.

2. Is the user is still pressing Ctrl then clicking in one to the dots already selected would deselect it (but will keep the other ones selected). This would be very useful for instance in the case of a plot in the forest with a small road passing through it. You would like to select everything first and then just de-select the few dots that fall on top of the road....This is a very common case when assessing plots.

3. Have a shortcut (for instance Ctrl+A) that selects all of the dots in the plot. If some dots are already classified then this shortcut selects only the non-classified plots.

4. Have shortcuts also for the classes. For instance one selects some dots from the plot, instead of having to find the Forest class in the right frame then one can click on the key F to classify them as forest. If you have a simple survey it would be easy to have one key (for instance first letter of the class) assigned per class and make the process faster.

**Comment by sirmspencer** [comment]
1. This is not possible.  You cannot overwrite the default browser behavior for a right click with out a control key.
2. This is already possible using the shift key.  Just as you can hold shift and click multiple points.
3/4. ctrl and letters are generally not possible either.  You can not overwrite system level actions. (Ctrl+A is already select all, but will select the entire page.  There is no way to overwrite this.)
