### ISSUE TITLE
Plots with random dots - dots too close together

### ISSUE THREAD

**Issue by herrtunante** [openforis/collect-earth-online#64]
In the plots where the dots are not systematic but random, each dot should have a buffer area (a couple of meters?) so that no other dot can be placed there. If the dots are very close together it makes the classification very complicated( selecting the right dot) and also looks bad.

Check the code from the Collect Earth circle plot generator which uses random positioning of the dots : https://github.com/openforis/collect-earth/blob/master/collect-earth/collect-earth-sampler/src/main/java/org/openforis/collect/earth/sampler/processor/CircleKmlGenerator.java

**Comment by sirmspencer** [comment]
Fixed in 560. Circles are still a little off, but that will be further improved later.
