### ISSUE TITLE
Updating widgets creates too many calls to the server

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#659]
Right now every update creates an update call for every widget, not just the one that is updated. And actually this runs twice.  The update is also called on page load.  Lets start by only updating one widget when once when it changes.

**Comment by billyz313** [comment]
I'll look into this, it sounds like it's not working properly if it's updating widgets that were not updated.

**Comment by rfontanarosa** [comment]
the main problem was that every time the layout changes it updated all the widgets, now it filters the list and update only the widget that has changed its layout.
