### ISSUE TITLE
Error creating a new project 

### ISSUE THREAD

**Issue by SofiaAcuna** [openforis/collect-earth-online#667]
Hello there!
I am having a problem creating my project and I dont now what it is. 

Thank you all!

![error_collect](https://user-images.githubusercontent.com/69603425/90063073-0aaccc80-dca6-11ea-9f13-a6a846ac8ed6.PNG)

**Comment by sirmspencer** [comment]
What options are you using to create the project?

**Comment by SofiaAcuna** [comment]
> What options are you using to create the project?

I am trying to use shps on Plot design and sample design. I put the column with the PLOTID, and SAMPLEID that the manual says, but I do not recognize the error.
