### ISSUE TITLE
Error with csv 

### ISSUE THREAD

**Issue by SofiaAcuna** [openforis/collect-earth-online#671]
Hello there!
I am uploading a csv file, with the columns that the program require but I still have a problem, and I dont know what it is. 
I attach the error and the plot file. 

Thanks!

![image](https://user-images.githubusercontent.com/69603425/90563833-9a98bd80-e161-11ea-8d0b-c927a71a6225.png)

[puntos_collect1.zip](https://github.com/openforis/collect-earth-online/files/5092738/puntos_collect1.zip)

**Comment by sirmspencer** [comment]
You are using semi colons as you delimiter.  Right now we only support commas.
