### ISSUE TITLE
error creating project

### ISSUE THREAD

**Issue by szandalos** [openforis/collect-earth-online#686]
I face a problem creating a new project in Collect Earth (https://collect.earth/create-project?institutionId=1200).  I get the error message "Error creating project.
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data".  Any idea what may be wrong?

**Comment by kdyson** [comment]
Hey! Can you please provide some more details? What parameters are you using for creating a new project?

Thanks!
