### ISSUE TITLE
export data needs to keep ancillary attribute columns

### ISSUE THREAD

**Issue by karistenneson** [openforis/collect-earth-online#705]
Hello,
We now have the option to view the ancillary data from a user defined csv or shapefile while labeling attributes in the map window. However, when I go to export the data, that is all stripped from the database. Can we maintain that additional data? It is needed to quickly run the calculations for area estimates based on mapped values.

**Comment by karistenneson** [comment]
@mspencer @gjohnson the sepal analysis workflow is broken because the columns with extra information (map classes) that are loaded into CEO are dropped when the user exports the data. Can we get this updated?

**Comment by sirmspencer** [comment]
@karistenneson Can you A) provide a sample set of data that replicates this bug, and B) test this on our new beta site?  The way you want it to be working should be the way it is working.
