### ISSUE TITLE
quantifying user skill

### ISSUE THREAD

**Issue by pweisberg** [openforis/collect-earth-online#72]
I gather that these discussions are already ongoing, but appropriate use of such outsourced data collection requires knowledge of the photo-interpretation skill of each user (especially if used broadly in a citizen science framework or involving high school students, undergrads, etc.) . It would be helpful if there were easy-to-use tools at the administrator level for constructing tests of user skill, given known 'gold standard' land-cover interpretations. Perhaps there could be outputs of user-specific classification accuracy that are specific to each land-cover type. This could help greatly with quantifying uncertainty prior to use of the dataset for training or validation of image classifications, or for direct use of the point data for statistical analysis independent. 
Simple (but of limited utility) would be to ask the users to rank their own skill level on the interface.

**Comment by sirmspencer** [comment]
We are wor
