### ISSUE TITLE
GeoDash Widgets not working

### ISSUE THREAD

**Issue by KMarkert** [openforis/collect-earth-online#73]
When analyzing plots, the widgets for GeoDash are set up but not displaying the time series or the imagery. No errors are given in the console either.

**Comment by billyz313** [comment]
Hey Kel, 
Can you please give me a link to the specific Geo-Dash?  I have noticed that sometimes there is just no images over specific sample locations.  This may be the case, or it may be something else, i'd like to debug and find out.

**Comment by KMarkert** [comment]
Hey Billy, here is the link to Geo-Dash for one project where it was not working: http://ceo.sig-gis.com/geo-dash?title%3DRLCMS%20Cambodia%26pid%3D37%26aoi%3D%5B105.21028778737363%2C12.498567572738537%2C105.21091341262637%2C12.499031727053108%5D%26daterange%3D%26bcenter%3D%7B%22type%22%3A%22Point%22%2C%22coordinates%22%3A%5B105.2106006%2C12.49879965%5D%7D%26bradius%3D15

I also attached a screenshot from what I could see.

I have seen this issue for multiple projects (RLCMS Vietnam, RLCMS Cambodia, RLCMS Thailand, RLCMS Laos, RLCMS Myanmar, and Ferlo pond for DCNN). Could it be too many people hitting CEO at one time with only one GEE account being served through the gee-gateway?

![screen shot 2017-08-03 at 3 35 28 pm](https://user-images.githubusercontent.com/11776290/28913312-c16d1a3a-7861-11e7-8503-12df4d8b2a50.png)
