### ISSUE TITLE
WMS allowed EPSG 

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#748]
Consider adding EPSG:4326 support for WMS feeds and serve a user-readable error when WMS servers don't support CEO's EPSG request. 

We have multiple users trying to attach WMS feeds and not knowing what is going wrong in CEO. They see their WMS works in QGIS or ArcMap and are configuring it correctly in CEO's interface, and it is failing silently due to EPSG issues.

**Comment by sirmspencer** [comment]
We could run a GetCapbilities request when adding imagery from the institution page to try and diagnose the issue.  Some users want a way to preview the imagery when adding it.  Combining those two requests, we could create a smarter widget for adding imagery that lets you test and modify the setting at the same time before saving.

**Comment by kdyson** [comment]
I think that makes sense!
