### ISSUE TITLE
Error when uploading large csv files

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#77]
I tried to create a project by uploading a csv file with 10,166 points and received an error that the project could not be created. However, when reduced the number of points to 200, I was able to create the project without any trouble.

**Comment by lambdatronic** [comment]
Hi Randy,

It seems that you either exceeded the file size upload limit (2MB) or overloaded our server's allotted memory. CEO currently supports creating projects of up to about 5000 points in size. We are currently working on expanding the database and server capacity to handle larger projects like yours. For now, perhaps you can divide your project data points into two projects and then combine their output CSVs for your own analyses.
