### ISSUE TITLE
Increase plots per project under some circumstances

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#786]
Request from Randy to allow 10-15k plots per project to allow countries to have one project instead of splitting data collection across multiple projects.

Possibly with a request/ approval process to avoid database bloat.

**Comment by sirmspencer** [comment]
Is he uploading files or having CEO generate the plots and samples?

**Comment by kdyson** [comment]
Uploading files, generally via .csv

**Comment by sirmspencer** [comment]
Yes, I can update the limits for files.  I dont see the same risk as when people are creating generic gridded projects.

**Comment by sirmspencer** [comment]
The plot limit for csvs is already 50K
