### ISSUE TITLE
Suggestion: Allow image source to be changed within a project

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#79]
When imagery is not available (or is cloudy, etc.) for a particular year of interest, it would be helpful to be able to change the image source to see images for different years while interpreting a particular plot. Along with this, I'd suggest allowing the user to see the date of the imagery and enable the user to record the date of the image.

**Comment by lambdatronic** [comment]
The imagery date is displayed at the bottom of the map in the attribution line.
As of yesterday, you may now switch between imagery sources for a given project.
