### ISSUE TITLE
CEODEV: Not clear when map doesn't update for Imagery Preview

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#794]
Imagery preview will only update under some circumstances (some by design?). Not clear which sources are broken and which won't let you pull large areas of data.

Also need to make it clear that the imagery preview window changes based on the default imagery. Consider changing box name to Default Imagery Preview.

![image](https://user-images.githubusercontent.com/6980290/97051373-eb4adf00-1533-11eb-987d-8a741fd08b12.png)

**Comment by sirmspencer** [comment]
The first issue is a much bigger topic. 

I like the title change.
