### ISSUE TITLE
Suggestion: Allow the user to access their own imagery using WMS or similar service

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#82]
For a project we are doing in Costa Rica, it will be critical to be able to use our own imagery in some cases. A WMS or similar service would probably be the easiest option. It would also be helpful to enable use of subscription services that users have purchased from companies such as Planet (Planet uses WMTS).

**Comment by lambdatronic** [comment]
This functionality is almost complete. Each institution may add its own imagery sources and projects under that institution may make use of any of these.

**Comment by herrtunante** [comment]
Just checked with a WMS service from Spain, seems to be working fine with a couple of bugs

The WMS service I used has these parameters:
Layer : PNOA
JSON : { "SERVICE":"WMS" ,"VERSION":"1.1.1","REQUEST":"GetMap","SRS":"EPSG:4326","WIDTH":"4096","HEIGHT":"4096","LAYERS":"PNOA","STYLES":"default","TRANSPARENT":"TRUE","FORMAT":"image/jpeg" }  

You can test it in a project over Spain.

THE BUGS:

1. There is no way to edit the imagery source. The process of adding WMS services is very error prone (e.g. misttyping the JSON parameters or changing the resolution or format) so you shopuld be able to edit the imagery sources (maybe the base ones like Bing Maps or Digital Globe should be " locked" )
http://i.imgur.com/0jW6gaw.png 

2. When I choose the PNOA as a basemap it works fine assessing plots, but if I go back to the project page (using hte Edit button) the basemap parameter appears empty, even though PNOA is in the list of avaliable sources. see images.

http://i.imgur.com/zurwJEF.png
http://i.imgur.com/gPUGd6u.png

**Comment by rhamilton03** [comment]
Hi Gary,

Thanks for the update. I'll try it out soon.

Randy
