### ISSUE TITLE
CEODEV: Recover password functionality broken

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#828]
User attempted to reset a password associated with an existing account on the ceodev website. Ceodev replied 'null'.

Two screenshots attached. The first shows existing account when user trying to sign up to the website. The second shows null error.

![image](https://user-images.githubusercontent.com/6980290/97478260-ead48e80-190d-11eb-8cbd-83f5b821f686.png)

![image](https://user-images.githubusercontent.com/6980290/97478270-f031d900-190d-11eb-91a7-f3600396e275.png)

**Comment by sirmspencer** [comment]
mail-config.edn was not configured correctly.  It should be updated now.
