### ISSUE TITLE
Can't delete a project

### ISSUE THREAD

**Issue by rhamilton03** [openforis/collect-earth-online#83]
I have been testing CEO and have created several projects. Some of them are no longer valid and I would like to delete them, but can't find a way to do so.

**Comment by lambdatronic** [comment]
To delete a project, log in as an administrator for the institution that owns the project. If you created the project, then your account has the correctly permissions already. Click the Edit button for that project on the home page to review the project details. Below the map, there is a button that will either be labeled "Publish Project", "Close Project", or "Archive Project". Each time you click it, the project's state is shifted to the next one in that list. Click Archive Project to delete the project.
