### ISSUE TITLE
CEODEV: Issues with .csv and .shp files for project creation

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#839]
Creating projects using these file types throws the following errors: 

- CSV File is empty, error importing file into SQL 
- Malformed plots CSV. Fields must include LON, LAT, PLOTID columns.
![image](https://user-images.githubusercontent.com/6980290/97496598-693d2a80-1926-11eb-8db9-9fdc61ebe1bf.png)

ETA: SHP file ok

Here are the files used:

[sample_csv.txt](https://github.com/openforis/collect-earth-online/files/5454775/sample_csv.txt)

**Comment by sirmspencer** [comment]
Fixed with #842
