### ISSUE TITLE
Random tests to identify malicious activity

### ISSUE THREAD

**Issue by tomdilts** [openforis/collect-earth-online#84]
I was showing this site to someone the other day and she brought up the idea of inserting a random test every once in a while in order to flag users who might be trying to intentionally mess up the data.  The test might consist of randomly inserting a known plot in every 20 or 30 plots and seeing if there is obvious maliciousness.  The user could be flagged as a bad user, and his/her data might be downweighted or dropped entirely.

**Comment by lambdatronic** [comment]
Thanks for your suggestion, Tom. The CEO team currently has a data validation scheme in the works that will enable project administrators to assess the quality of users' inputs. This should be rolling out sometime next month.
