### ISSUE TITLE
CEODEV: Unexpected behavior when editing shp project

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#841]
THis may happen for other types of projects as well.

If you create a shapefile project, then go to edit it, clicking the 'next' button makes you go to the review screen. also only 'project overview' is in the top navigation.

![image](https://user-images.githubusercontent.com/6980290/97500189-66ddcf00-192c-11eb-833a-8f65eb69444e.png)

**Comment by sirmspencer** [comment]
This is not an issue. Full edit has not yet been deployed.
