### ISSUE TITLE
example .csv and .shp files

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#856]
In parallel with #855 , consider providing example .csv and .shp files (known good) that users can use as templates.

Also useful for testing.

**Comment by sirmspencer** [comment]
Can you please create the files that you wish to be used as and example?

**Comment by sirmspencer** [comment]
[example-external-files.zip](https://github.com/openforis/collect-earth-online/files/5703993/example-external-files.zip)

**Comment by sirmspencer** [comment]
- [ ] Remove the old test files, they have errors in them (resources/test_data)
- [ ] Unzip the attached file and add them to resources/public/test_data
- [ ] in /src/clj/org/openforis/ceo/js/project/PlotDesign and /src/clj/org/openforis/ceo/js/project/SampleDesign add a link under each file selector that says "Download example plot shp file".  Only show this link when the file selector is visible.

**Comment by gtondapu** [comment]
I have made the changes. After I did some testing I found the following results. Is everything good with Plot shape file?

uploading plots csv and samples csv - works
uploading plots csv and samples shp - works
uploading plots shp and samples shp - would not work
uploading plots shp and samples csv- would not work
