### ISSUE TITLE
CEODEV: Typos etc.

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#861]
Git hub just lost all my wizard suggestions so hopefully I'll remember them:

- [ ] Plot Generation subheading present but no area of interest heading. Suggest removing or adding area of interest heading

- [ ] Creating AOI in the map difficult/impossible if imagery doesn't show. suggest adding a default line map or something to address.

- [x] Diameter (m) shown for both circle and square plot shapes

- [x] Space needed for sample generation preview text (Each plot will contain around 1 **samples.There** will be around 25 total samples in the project.)

- [ ] Sample generation subheading the only other wizard panel that has a subheading. suggest removing. also suggest 'sample generation' instead of 'sample generation for collection'

**Comment by sirmspencer** [comment]
> * [ ]  Creating AOI in the map difficult/impossible if imagery doesn't show. suggest adding a default line map or something to address.

This is an existing issue that will have to be addressed later

**Comment by kdyson** [comment]
- [ ] Add clarifying sub-text under "Allow users to draw their own samples". I suggest something along these lines: "Enable this to allow users to draw and label points, lines, and polygons during data collection"

**Comment by kdyson** [comment]
- [ ] On the sample generation page, if you specify a grid distance larger than your plot the wizard will say "Each plot will contain around 1 samples." but then you cannot move on because you get the error "The sample spacing must be less than the plot width." I think the error is good and it would be great if the sample preview would match.

**Comment by sirmspencer** [comment]
> * [ ]  On the sample generation page, if you specify a grid distance larger than your plot the wizard will say "Each plot will contain around 1 samples." but then you cannot move on because you get the error "The sample spacing must be less than the plot width." I think the error is good and it would be great if the sample preview would match.

Can you make this a separate issue?  We dont include any error handling messaging in the count messages (plot or sample).  This will be a bigger task if we need to add active error messaging.
