### ISSUE TITLE
Add imagery to Project Details

### ISSUE THREAD

**Issue by Abena2020** [openforis/collect-earth-online#870]

**Comment by Abena2020** [comment]
Hi, please is it possible to include additional imagery to my project after the project has been created?
![Screenshot (147)](https://user-images.githubusercontent.com/73937940/98103433-e61f5580-1e8c-11eb-8a8c-96c5e938a762.png)

**Comment by kdyson** [comment]
Hi Abena, If you click on "edit project" it will take you to the wizard. If you click "Next" you will navigate to the Imagery pane and you can add additional imagery.

Matt, I was thinking this yesterday while we were troubleshooting the Planet issue--I think adding imagery will be one of the most common changes needed by project managers and it might be worth adding an easier way to add imagery...

**Comment by sirmspencer** [comment]
> Matt, I was thinking this yesterday while we were troubleshooting the Planet issue--I think adding imagery will be one of the most common changes needed by project managers and it might be worth adding an easier way to add imagery...

Im open to suggestions.  Any sort of editing from the review page will be confusing because everything cant be edited their.  I was planning on adding a little edit icon to each piece which would then jump the user to the correct step in the wizard to edit.

**Comment by kdyson** [comment]
I like the idea of edit icons--matches what we have on the Institution page for e.g. imagery.
