### ISSUE TITLE
CEODEV: adding users

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#874]
Checking for strange error vs. user error.

Admin of https://ceodev.servirglobal.net/review-institution?institutionId=365 reports being unable to add users to their institution. I can add the email addresses to my own institution (356). Admin reports that they are getting the 'no such user' error.

**Comment by sirmspencer** [comment]
Can you please give me one email that they cannot add, as an example.

**Comment by sirmspencer** [comment]
I was able to add the users in question with no problem.  They look like new users so its possible that the admin tried to add them too soon.
