### ISSUE TITLE
Improvements in the Help Text (purple questionmark) 

### ISSUE THREAD

**Issue by carmenmorales-fao** [openforis/collect-earth-online#881]
**Collection Help**:
The picture is not readable in the card where you show all the enumerated possibilities of data collection. 

**Create Project Help**:
The picture is not visible in the card where it explains how to specify the boundaries. 
I would elaborate a bit in the card where you explain how to create the survey questions and explain the differences between button, input, radiobutton and dropdown.

**Comment by kdyson** [comment]
- [ ] Add examples for survey design.
- [ ] Replace image for survey design. 
- [ ] 'Advanced survey design' still referenced in survey creation slide.

- [ ] Add examples for project rules.

- [ ] Add more info for proactive sampling; particularly use case and hints about use.

**Comment by kdyson** [comment]
- [ ] Add proactive sampling for data collection

**Comment by kdyson** [comment]
Updated; see here: https://drive.google.com/drive/u/0/folders/1bWU8RnZ6MSQqNURqzhp8sB9Zg5Hp4c36

**Comment by lambdatronic** [comment]
Help slides still need to be created for these tasks:

1. *Institution:* information will be created to describe how to setup
   and manage an institution page.

2. *Imagery and time series options:* Information will be created
   about both publicly and commercially available high-resolution
   image data sets, how to connect private WMS feeds into the users’
   institution page, and how to create some suggested default time
   series Landsat and Sentinel image chips and charts.

3. *Project Management:* material will be created that describes the
   data download process, how to integrate inventory data from Collect
   Earth Online with the mapping and area estimation modules within
   SEPAL.

**Comment by kdyson** [comment]
Adding Institution and Imagery and time series options to the folder now.

The Project Management slide can duplicate the last slide from project creation. We can discuss if additional detail is needed: https://docs.google.com/document/d/1Lp1wt-fuYzCn0QXG__djxGduxN-60dyoOvZ6uTYupEI/edit

**Comment by kdyson** [comment]
The Institution and Imagery addition are covered now. For imagery addition I don't believe there are image chips or charts--that should be the Geo-Dash which already has a help function
