### ISSUE TITLE
Problem defining the samplings in the new proactive sampling feature option

### ISSUE THREAD

**Issue by carmenmorales-fao** [openforis/collect-earth-online#882]
How can I define the sampling points once I have created a project selecting “None” for Spatial Distribution on the Sample Generation part of the project setup? In the project overview, it says you can draw them, but I was not able to draw them by myself. 

If I try to answer the survey questions without sampling points it says "You must make a selection after some samples have been answered." It should tell you how to draw the samplings.

**Comment by sirmspencer** [comment]
Click the draw mode button
![image](https://user-images.githubusercontent.com/33734037/98612309-bd41fa80-22a8-11eb-8457-d505169771f8.png)

**Comment by carmenmorales-fao** [comment]
Thanks a lot!
