### ISSUE TITLE
GEODASH - Use templates or geodash conbfigurations from other projects

### ISSUE THREAD

**Issue by herrtunante** [openforis/collect-earth-online#89]
Normal/Beginner users will be at a loss when trying to configure GeoDash.

It would be much easier if the user is given a few options when starting the geodash configuration (as we do when starting a new Collect Earth project)

The options should be (more or less, we will need to define exactly what the pre-existing options should be)

- 1. Geodash with NDVI charts and Landsat 8, Landsat 7 and Sentinel-2 imagery
- 2 Geodash with Sentinel-1 and comparisons
 -3 Copy geodash from another project (import geodash json configuration)
 -4 Start from scratch

**Comment by billyz313** [comment]
Thank you, this is actually in development currently and should be rolled out in the near future

**Comment by billyz313** [comment]
This has been completed, to use at the top of the Create Project in the section:
Use Project Template (Optional)
Select the project that you would like to copy the GeoDash from and check the box: Copy Template Widgets
