### ISSUE TITLE
incorrect gridded sample design

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#897]
This was reported in CEODEV but should hold b/c it was migrated to live over the weekend.

See project : https://ceodev.servirglobal.net/collection?projectId=4639

Sampling design should be points 200 km apart. This appears true N/S but there are too many points E/W. In addition, the gridding stops 2/3 of the way across the AOI.

I am working on replicating the issue given the same AOI and gridding parameters, but the project is large (lots of samples/points) and thus is taking a while.

**Comment by sirmspencer** [comment]
The issue is that our project overview cannot handle projects this large so some of the plots get cut off.  There is already an issue to optimize the project overview and show more plots.
