### ISSUE TITLE
Gridded sample spacing less than 10m giving error.

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#901]
With 30m square plots, sample spacing under 10 m returns the error: "The sample spacing must be less than the plot width." 

Sample spacing over 10 m does not return an error. 

Playing around with the size of the square plot: 20m plots with 5 m spacing returns an error. 50m square plots with 5 m sample spacing has no error.

**Comment by sirmspencer** [comment]
Fixed with #903
