### ISSUE TITLE
Usability: Next Plot/Save Assignment/Flag plot buttons --> unification

### ISSUE THREAD

**Issue by herrtunante** [openforis/collect-earth-online#92]
The current buttons and flow is confusing and makes the user waste time.

These buttons should be condensed into one button called "Save" 

If the user has not filled any info the label on the button should be "Save - No imagery" or "Save-Flag Plot"

If the user is filling info the button should be then renamed to "Save" but stay disabled

If the user has finished assigning the categories to each point then the button should be enabled.

There should be no further message once the plot is saved. Just show a progress bar/circle on top of the map saying something like " Saving data..." while moving to the next plot.

**Comment by sirmspencer** [comment]
This functionality has been significantly updated.  There is an option to go back and forth without saving and go through previously analyzed plots.  The user will not be able to save data to the database until all questions are answered.
