### ISSUE TITLE
Update gee-gateway's README

### ISSUE THREAD

**Issue by lambdatronic** [openforis/collect-earth-online#923]
- Step 1: Gain admin permissions on the gee-gateway repo
   - Option 1: Contact Daniel at FAO to get admin permissions on the current gee-gateway repo.
   - Option 2: Create a new gee-gateway repo under the Github SERVIR group, and update the link to it in CEO's README.
- Step 2: Grant Matt and Gary write permissions, so that we can submit PRs.
- Step 3: Gary and Matt submit their README PRs:
  - Document how to create and setup TLS certificates
  - Document how to start/stop/enable nginx (emperor.uwsgi service)
  - Document how to accept HTTP traffic on port 8881
- Step 4: Review and merge in Matt and Gary's PRs.

**Comment by sirmspencer** [comment]
Billy already added the repo here https://github.com/SERVIR/gee-gateway

The readme should be up to date.

**Comment by sirmspencer** [comment]
I just went through the set up steps again and updated the readme.  Everything looks good to me.

**Comment by sirmspencer** [comment]
Re verified when deploying the new dev server.
