### ISSUE TITLE
If WMS "Additional WMS Params (as JSON object)" does not have wrapping {}, add them.

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#955]
The two scenarios to test are
1. A blank input box should result in {} which is a valid entry
2. Comma separated fields should add wrapping {} `"var": 12, "num": 8` -> `{"var": 12, "num": 8}`
3. Comma separated fields, missing quotes should add quotes `{var: 12, num: 8}` -> `{"var": 12, "num": 8}`

**Comment by rfontanarosa** [comment]
no problem with the first one, we can use the sanitizer logic.

for the second one it's a tricky thing, we can sanitize it in the same function but we can't use keys without double quotes (the current validator wants them). we can use a complex function to creare a valid json from "var: 12, num: 8" like this:

`{${url.split(",").filter(v => v !== "").map(v => v.split(":")).map(([k, v]) => `"${k.replace(/[ "']/g, "")}": ${v}`).join(",")}}`

**Comment by sirmspencer** [comment]
That sounds good so far.  You can create regex patterns to test against to know how to sanitize the data.

**Comment by sirmspencer** [comment]
Use 
```
sanitizer: json => `{${json
                    .trim()
                    .replace(/[{}]/g, "")
                    .split(",")
                    .filter(u => u !== "")
                    .map(u => {
                        const [k, v] = u.split(":");
                        return v && `"${k.replace(/[ "']/g, "")}": "${v.replace(/[ "']/g, "")}"`;
                    })
                    .join(",")}}"`,
```
