### ISSUE TITLE
Sanitize and validate before stacking params

### ISSUE THREAD

**Issue by sirmspencer** [openforis/collect-earth-online#964]
You will need to update `stackParams` to take `imageryParams` and then sanitize and validate `this.state.newImageryParams` and pass it to `stackParams`

**Comment by rfontanarosa** [comment]
this issue has been solved by https://github.com/openforis/collect-earth-online/pull/974.

**Comment by rfontanarosa** [comment]
this issue has been solved by #974.

**Comment by rfontanarosa** [comment]
fixed by https://github.com/openforis/collect-earth-online/pull/982
