### ISSUE TITLE
Geo-dash chart with longer time window

### ISSUE THREAD

**Issue by nguyenhanhquyen** [openforis/collect-earth-online#99]
Hi,

Could the NDVI, NDWI chart on Geo-Dash has longer time window, i.e chart show change from 2000 to 2016, and when zoom in detailed we can see at monthly for crops (like what it shows now).
that would be more helpful to identify change and tell if forest are plantation.

Thanks

**Comment by billyz313** [comment]
The Geo-Dash graph widgets are now configurable by the admin to display any range and can also be zoomed.
