### ISSUE TITLE
Issues when adding multiple Survey Rules

### ISSUE THREAD

**Issue by kdyson** [openforis/collect-earth-online#996]
When creating multiple survey rules of the type Incompatible Answers there are at least two issues. In testing, both are intermittent issues (or I didn't immediately notice a pattern). They may be related to the very large surveys and number of survey rules implemented.

1. When generating a new rule, sometimes you cannot change the selection. For example, if Q1 and A1 remain the same and you want to change A2, CEO won't allow the values for A2 to change (clicking on the dropdown arrow does nothing). A user reported that this can sometimes be fixed by changing one of the other Q/A selections. (Here's their exact text: _The problem I am encountering is when generating a new rule (incompatible answer) as it does not change the new selection and remains in the last selection of the previous rule. For example, if question 1 and answer 1 remain the same and you want to change answer 2, the program keeps the values of answer 2 from the previous rule. If answer 2 is being changed, in the drop-down list the first option does not work, keeping the values of the last option of the previous rule. This only seems to be resolved by going to the second option in the drop-down list of answer 2. Once it has been selected and added as a new rule, it is possible to proceed with the first option of the drop-down list that was not selectable before_.)
2. Sometimes when you choose Q1, which Q2 is selected changes. 

Here is the project where I was experimenting: https://collect.earth/review-project?projectId=19707

**Comment by gtondapu** [comment]
I have made changes and pushed the code to the repository. Looked like having a default option of 'None' for the dropdowns eliminated the issues that were described.

**Comment by kdyson** [comment]
Great! 

The user just sent me a follow up message: "I have also noticed that when making a new rule (eg incompatible answers), it changes the values of the previously made rules of the type "Sum of answers" and "Matching sums", changing the value set from 100 to 0."

@gtondapu Could you please check that your fix addresses this issue as well?
